[phases.setup]
nixPkgs = ["python311", "gcc", "nodejs", "npm", "postgresql", "openssl"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd theme && npm install && npm run build",
    "cd .."
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python manage.py tailwind build",
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && cd /app && python manage.py migrate && daphne -b 0.0.0.0 -p $PORT marital_website.asgi:application"
