# Generated by Django 5.1.6 on 2025-03-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='message',
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('liked', 'Liked'), ('rejected', 'Rejected'), ('matched', 'Matched')], default='pending', max_length=10),
        ),
    ]
