# Generated by Django 5.1.6 on 2025-04-21 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0004_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='name',
            new_name='couple_name',
        ),
    ]
