# Generated by Django 5.1.6 on 2025-04-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0005_rename_name_testimonial_couple_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
