# Generated by Django 5.1.6 on 2025-04-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marital', '0007_testimonial_is_approved_alter_testimonial_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='user',
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='couple_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
